# Logging configuration
[log]
verbose = true
console = true
level = "debug"

[discord]
botToken = ""
removeCommands = true
guildId = ""
adminRoleIds = []

[firebase]
projectId = ""
serviceAccountFilePath = ""